// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJXoIyuE80YQplTu0ejqOLOmLY7zvamg',
    appId: '1:503804894995:web:501f688bb46170744184e6',
    messagingSenderId: '503804894995',
    projectId: 'mess-bf98c',
    authDomain: 'mess-bf98c.firebaseapp.com',
    storageBucket: 'mess-bf98c.appspot.com',
    measurementId: 'G-FHKSYDFN2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2mgX5IINqBslX493luD5mMuPGu6Vp5U',
    appId: '1:503804894995:android:39c16d70b3060dc74184e6',
    messagingSenderId: '503804894995',
    projectId: 'mess-bf98c',
    storageBucket: 'mess-bf98c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUGgzpoQRdTncxyKqnaHp7VQo1CCH4h0',
    appId: '1:503804894995:ios:1136a345a5d63adf4184e6',
    messagingSenderId: '503804894995',
    projectId: 'mess-bf98c',
    storageBucket: 'mess-bf98c.appspot.com',
    iosClientId: '503804894995-q44gauaobk7mh9sm2h370lf7ktr3k908.apps.googleusercontent.com',
    iosBundleId: 'com.example.messapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHUGgzpoQRdTncxyKqnaHp7VQo1CCH4h0',
    appId: '1:503804894995:ios:1136a345a5d63adf4184e6',
    messagingSenderId: '503804894995',
    projectId: 'mess-bf98c',
    storageBucket: 'mess-bf98c.appspot.com',
    iosClientId: '503804894995-q44gauaobk7mh9sm2h370lf7ktr3k908.apps.googleusercontent.com',
    iosBundleId: 'com.example.messapp',
  );
}
